### PR TITLE
Bug/176 gatling el

### LINKED ISSUE #32: CI: Error if API Key contains "#{"
API Key seems to be interpreted as Gatling EL if it contains "#{" subsequence

https://github.com/agera-edc/MinimumViableDataspace/runs/6654845967?check_suite_focus=true

```
510
    io.gatling.core.session.el.ElParserException: Failed to parse K#{44P4jpoi*bH4X with error ''}' expected but end of source found'
[511](https://github.com/agera-edc/MinimumViableDataspace/runs/6654845967?check_suite_focus=true#step:5:512)
    	at io.gatling.core.session.el.ElCompiler.io$gatling$core$session$el$ElCompiler$$parseEl(ElCompiler.scala:298)
[512](https://github.com/agera-edc/MinimumViableDataspace/runs/6654845967?check_suite_focus=true#step:5:513)
    	at io.gatling.core.session.el.ElCompiler$.parse(ElCompiler.scala:240)
[513](https://github.com/agera-edc/MinimumViableDataspace/runs/6654845967?check_suite_focus=true#step:5:514)
    	at io.gatling.core.session.el.ElCompiler$.compile(ElCompiler.scala:243)
[514](https://github.com/agera-edc/MinimumViableDataspace/runs/6654845967?check_suite_focus=true#step:5:515)
    	at io.gatling.core.session.el.package$El$.el$extension(package.scala:27)
[515](https://github.com/agera-edc/MinimumViableDataspace/runs/6654845967?check_suite_focus=true#step:5:516)
    	at io.gatling.javaapi.core.internal.Expressions$.toStringExpression(Expressions.scala:89)
[516](https://github.com/agera-edc/MinimumViableDataspace/runs/6654845967?check_suite_focus=true#step:5:517)
    	at io.gatling.javaapi.core.internal.Expressions.toStringExpression(Expressions.scala)
[517](https://github.com/agera-edc/MinimumViableDataspace/runs/6654845967?check_suite_focus=true#step:5:518)
    	at io.gatling.javaapi.http.HttpProtocolBuilder.header(HttpProtocolBuilder.java:280)
[518](https://github.com/agera-edc/MinimumViableDataspace/runs/6654845967?check_suite_focus=true#step:5:519)
    	at org.eclipse.dataspaceconnector.system.tests.local.TransferLocalSimulation.<init>(TransferLocalSimulation.java:49)
[519](https://github.com/agera-edc/MinimumViableDataspace/runs/6654845967?check_suite_focus=true#step:5:520)
    	at org.eclipse.dataspaceconnector.system.tests.local.BlobTransferLocalSimulation.<init>(BlobTransferLocalSimulation.java:22)
```

### LINKED ISSUE #176: CI: Error if API Key contains "#{"
API Key seems to be interpreted as Gatling EL if it contains "#{" subsequence

https://github.com/agera-edc/MinimumViableDataspace/runs/6654845967?check_suite_focus=true

```
510
    io.gatling.core.session.el.ElParserException: Failed to parse K#{44P4jpoi*bH4X with error ''}' expected but end of source found'
[511](https://github.com/agera-edc/MinimumViableDataspace/runs/6654845967?check_suite_focus=true#step:5:512)
    	at io.gatling.core.session.el.ElCompiler.io$gatling$core$session$el$ElCompiler$$parseEl(ElCompiler.scala:298)
[512](https://github.com/agera-edc/MinimumViableDataspace/runs/6654845967?check_suite_focus=true#step:5:513)
    	at io.gatling.core.session.el.ElCompiler$.parse(ElCompiler.scala:240)
[513](https://github.com/agera-edc/MinimumViableDataspace/runs/6654845967?check_suite_focus=true#step:5:514)
    	at io.gatling.core.session.el.ElCompiler$.compile(ElCompiler.scala:243)
[514](https://github.com/agera-edc/MinimumViableDataspace/runs/6654845967?check_suite_focus=true#step:5:515)
    	at io.gatling.core.session.el.package$El$.el$extension(package.scala:27)
[515](https://github.com/agera-edc/MinimumViableDataspace/runs/6654845967?check_suite_focus=true#step:5:516)
    	at io.gatling.javaapi.core.internal.Expressions$.toStringExpression(Expressions.scala:89)
[516](https://github.com/agera-edc/MinimumViableDataspace/runs/6654845967?check_suite_focus=true#step:5:517)
    	at io.gatling.javaapi.core.internal.Expressions.toStringExpression(Expressions.scala)
[517](https://github.com/agera-edc/MinimumViableDataspace/runs/6654845967?check_suite_focus=true#step:5:518)
    	at io.gatling.javaapi.http.HttpProtocolBuilder.header(HttpProtocolBuilder.java:280)
[518](https://github.com/agera-edc/MinimumViableDataspace/runs/6654845967?check_suite_focus=true#step:5:519)
    	at org.eclipse.dataspaceconnector.system.tests.local.TransferLocalSimulation.<init>(TransferLocalSimulation.java:49)
[519](https://github.com/agera-edc/MinimumViableDataspace/runs/6654845967?check_suite_focus=true#step:5:520)
    	at org.eclipse.dataspaceconnector.system.tests.local.BlobTransferLocalSimulation.<init>(BlobTransferLocalSimulation.java:22)
```

### PR DESCRIPTION
**Pull request by algattik**
Avoid API Key string being interpreted as Gatling Expression Language.

Closes agera-edc/MinimumViableDataspaceFork#32

### CODE REVIEW

File: system-tests/src/test/java/org/eclipse/dataspaceconnector/system/tests/local/TransferLocalSimulation.java [hunk 1]
```diff
@@ -46,7 +46,7 @@ public class TransferLocalSimulation extends Simulation {
     public TransferLocalSimulation(TransferRequestFactory requestFactory) {
         var httpProtocol = http
                 .baseUrl(CONSUMER_MANAGEMENT_URL)
-                .header(API_KEY_HEADER, API_KEY);
+                .header(API_KEY_HEADER, s -> API_KEY); // use the Function form to avoid special characters to be interpreted as Gatling Expression Language
```
Comment (pkirch) [inline system-tests/src/test/java/org/eclipse/dataspaceconnector/system/tests/local/TransferLocalSimulation.java:49]: Do you know why using a lambda resolves this issue?
I would assume the ´header´ function still gets the same value from `API_KEY`.

Comment (algattik) [reply system-tests/src/test/java/org/eclipse/dataspaceconnector/system/tests/local/TransferLocalSimulation.java:49]: See javadoc. Using the string form causes EL resolution, with the Function form you don't need EL (or you can call it explicitly if needed). I've tested manually that it works.

**Review by cpeeyush — APPROVED** [review]

**Review by pkirch — APPROVED** [review]
